### ISSUE TITLE
Release 0.2.9 without configure.zcml

### ISSUE THREAD

**Issue by idgserpro** [zopyx/xmldirector.connector#62]
pypi release `0.2.9` is without `configure.zcml`:

https://pypi.org/project/xmldirector.connector/0.2.9

[MANIFEST.in](https://github.com/zopyx/xmldirector.connector/blob/0ca49a6ab0333dbaa97f6a12439050c0184dc106/MANIFEST.in) is wrong.

@zopyx

**Comment by zopyx** [comment]
opps..

**Comment by zopyx** [comment]
Can you try 0.3.0 please? Python 2 support has been removed in 0.3.X 😈

**Comment by idgserpro** [comment]
@zopyx I did the PR #63

**Comment by idgserpro** [comment]
>Can you try 0.3.0 please?

The version 0.3.0 works, Tanks!
