### ISSUE TITLE
Error when trying to list webdav directory

### ISSUE THREAD

**Issue by idgserpro** [zopyx/xmldirector.connector#64]
I configure the `xmldirector.connector` to access a webdav. When I access the view of a `Connector`, the error below occurs when trying to list the contents of the folder:

```
2020-11-05 17:11:06,611 ERROR   [Zope.SiteErrorLog:252][waitress-1] 1604607066.61069370.025573435804350564 http://localhost:12020/Plone/pasta-webdav/@@connector-folder-contents
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 359, in publish_module
  Module ZPublisher.WSGIPublisher, line 262, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module xmldirector.connector.browser.connector, line 302, in folder_contents
  Module xmldirector.connector.browser.connector, line 253, in sort_key
TypeError: must be str, not NoneType
```

@zopyx any tip?

**Comment by zopyx** [comment]
Not sure...how to reproduce?

**Comment by idgserpro** [comment]
I'm using Apache + mod_dav

The problem is that the `item.name` variable:

https://github.com/zopyx/xmldirector.connector/blob/f05b50497f8a1fab7de145663ecee43f4094cbbd/xmldirector/connector/browser/connector.py#L253

 is coming `None`.

This is because the Apache webdav is not returning the `displayname` property. The webdav client used by `xmldirector.connector` needs this property to define the name variable:

https://github.com/appetito/webdav-client-python-2/blob/243520141ddea6a0664121f117fdf1bc874085d6/webdav2/client.py#L586

I don't know if I could configure mod_dav to return this property.

**Comment by zopyx** [comment]
I added a workaround for catching this  sort_key issue in 0.3.1.
Please re-open if the error persists.
